### ISSUE TITLE
Страници във Facebook на медиите от списъка?

### ISSUE THREAD

**Issue by ignisf** [openmediabg/dancewithme#13]
Попаднах на [статия](https://www.bivol.bg/peevski-facebook.html), която ме накара да се замисля, че освен основните си сайтове, голяма част от медиите вероятно имат и страници във Facebook (например станалата популярна миналия ден страница на tv7). Дали няма да е хубаво да филтрираме и тях?

**Comment by mpeshev** [comment]
звучи ми като много добра идея

**Comment by ignisf** [comment]
Подхвърлят ми и идеи за филтриране на timeline-а на Facebook.

**Comment by mpeshev** [comment]
https://www.bivol.bg/peevski-facebook.html

**Comment by mitio** [comment]
Аз съм "за" да го добавим това. Аз ще се заема с хром разширението, но ще е или към края на деня, или утре (освен ако някой не ме изпревари).

**Comment by kunev** [comment]
Хрома е горе-долу готов, малко остава само.

Искаме ли по-различен warning да се показва за fb страници(струва ми се логично)?
За да можем да детектваме какво да се показва съм пипнал малко return value-то на checkPeevskiDomain(може би трябва и да се прекръсти, предвид, че не чеква само домейн в тоя си вид вече) и ш'се наложи пипане и по другите browser specific части. Довечера ш'а пусна и pull request.

**Comment by mitio** [comment]
Направи един PR, в който да виждаме всички промени дотук и да дискутираме кода.

Какъв текст си представяш за Facebook страници? Принципно е добре да е различен, наистина, понеже това не е журналистика, а са други неща... Измисли и предложи нещо.

**Comment by ignisf** [comment]
@kunev, хвърли и едно око на #9

**Comment by ignisf** [comment]
Това е имплементирано във версия 0.2.0
