### ISSUE TITLE
Под Firefox/Linux стрелките в бутоните се показват като кодове FFE9 и FFEB

### ISSUE THREAD

**Issue by ignisf** [openmediabg/dancewithme#14]
![issue](http://i.imgur.com/QUvd31u.png)

Ето как изглежда:
![issue](http://i.imgur.com/W9UIjFD.png)

Шрифт Ubuntu

**Comment by mitio** [comment]
Някой може ли да каже дали `&larr;` и `&rarr;` се виждат окей?

**Comment by ignisf** [comment]
Да, показват се ОК.

**Comment by gsamokovarov** [comment]
При мен се виждат OK при Ubuntu 12.10 и фонтове по подразбиране.

**Comment by ignisf** [comment]
@gsamokovarov, `closes #14` в commit съобщението би затворило автоматично issue-то :)

**Comment by gsamokovarov** [comment]
:+1: Знам, но все пак исках да изчакам малко, преди да го затворя :)

Да пусна 0.1.3 за обратна връзка?
