### ISSUE TITLE
Неработещ "все пак ще продължа" - Chromium, Ubuntu

### ISSUE THREAD

**Issue by mpeshev** [openmediabg/dancewithme#16]
Един колега репортна проблем с неработещ "все пак ще продължа" бутон под Chromium, Ubuntu:

https://twitter.com/ju/status/350969298430332930

Малко повече детайли от него:

Версия на Chromium-а: 25.0.1364.160
JS грешка на ДАНСwithme страницата:

```
Uncaught TypeError: Object #<Object> has no method 'sendMessage' init.js:8 
<chrome-extension://lmcpmmnecclemnhobkplkgpjjddgnkej/init.js>document.getElementById.onclickinit.js:8 
<chrome-extension://lmcpmmnecclemnhobkplkgpjjddgnkej/init.js>
```

**Comment by ignisf** [comment]
Ох... Как си спомням защо мигрирах от Ubuntu... Някой може ли да се опита да репродуцира бъга? Аз съм с хром 28...

**Comment by mpeshev** [comment]
И аз съм с тоя хром, а това е хромиум, но не съм качвал отделно за тест

**Comment by GeorgeSG** [comment]
Със Chromium 28.0.1500 под Ubuntu 13.04 нямам такъв проблем. :)

**Comment by ignisf** [comment]
Смятам, че можем да затворим това

**Comment by gsamokovarov** [comment]
:+1:
