### ISSUE TITLE
Лиценз на проекта

### ISSUE THREAD

**Issue by ignisf** [openmediabg/dancewithme#22]
Знам, че е подробност, но ме човърка като не сме посочили лиценз. GPLv3? [CC-BY-NC-SA](http://creativecommons.org/licenses/by-nc-sa/2.5/bg/)?

**Comment by mitio** [comment]
Правилно. Става.

**Comment by gsamokovarov** [comment]
Ах, не може ли да сме по-либерални и да ползваме MIT? Всмисъл, не знам кой ще седне да прочете GPLv3.

**Comment by mitio** [comment]
Аз не възразявам и на по-либералния вариант.

Мисля си следното - доколкото ми е известно, MIT позволява и комерсиална употреба. Каква би могла да е тази употреба? Може би някой да използва нашия труд тук, за да направи приставка за блокиране на сайтове, примерно, и да я продава. Имаме ли нещо против? Аз лично, за кода за хром, не мисля, че бих възразил. Вие се изпотихте доста над FF кода, кажете си вие как го виждате това.

**Comment by ignisf** [comment]
@mpeshev, @WebCrusader нещо против MIT?

**Comment by mpeshev** [comment]
за мен е окей всеки GPL-compatible вариант
