### ISSUE TITLE
Име на проекта

### ISSUE THREAD

**Issue by gsamokovarov** [openmediabg/dancewithme#28]
В момента се подвизаваме като `#ignorepeevski`, `#ДАНСwithme`, `dancewithme`. Може би и други...

Дайте да се спрем на едно име, примерно `#ignorepeevski` и така да се подвизаваме навсякъде. Ако преименуваме GitHub проекта, https://github.com/open-media/dancewithme/ ще пренасочва към новото име.

@mitio, @ignisf мнения?

**Comment by mitio** [comment]
Аз лично харесвам `dancewithme` повече от `#ignorepeevski`, понеже ми се струва по-общо и смятам, че в бъдеще можем да развием това разширение така, че да предупреждава за проблеми със собственост на медии (не само такива от групата на Пеевски), или за проблеми с обективността на статии.

**Comment by mitio** [comment]
@WebCrusader, кажи си и ти мнението :)

**Comment by ignisf** [comment]
:+1: за `dancewithme`
