### ISSUE TITLE
Некоректни съвпадения на сайтовете, дължащо се на Regex-проверките

### ISSUE THREAD

**Issue by mialy** [openmediabg/dancewithme#31]
Накратко под Firefox разширението блокира monitoribg.com, като го смята за monitor.bg.

Във файла \dancewithme\lib\blocked_domains.js, масив blockedDomains съдържа неескейпнати точки в домейните.

Възможно просто решение е реда:
var urlPattern = new RegExp("^http(s)?\:\/\/([^\/]+\.)?" + blockedDomains[i]);

да се замени с:
var urlPattern = new RegExp("^http(s)?\:\/\/([^\/]+\.)?" + blockedDomains[i].replace(".", "\."));

Поне при мен по този начин вече работи коректно.

Поздрави!

**Comment by mitio** [comment]
Оправено в 4ecfde6.
